---
name: Lint and Test Charts
on:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - id: get-chart
        name: Get modified charts
        env:
          DIFF_URL: "${{github.event.pull_request.diff_url}}"
          TEMP_FILE: "${{runner.temp}}/pr-${{github.event.number}}.diff"
        run: |
          # This request doesn't consume API calls.
          curl -Lkso $TEMP_FILE $DIFF_URL
          files_changed="$(sed -nr 's/[\-\+]{3} [ab]\/(.*)/\1/p' $TEMP_FILE | sort | uniq)"
          # Adding || true to avoid "Process exited with code 1" errors
          charts_dirs_changed="$(echo "$files_changed" | xargs dirname | grep -o "charts/[^/]*" | sort | uniq || true)"
          echo $charts_dirs_changed
          # Using grep -c as a better alternative to wc -l when dealing with empty strings."
          num_charts_changed="$(echo "$charts_dirs_changed" | grep -c "charts" || true)"
          echo $num_charts_changed
          if [[ "$num_charts_changed" -gt "1" ]]; then
            echo "error=Multiple chart changes detected in charts folder." >> "$GITHUB_OUTPUT"
            echo "result=error" >> "$GITHUB_OUTPUT"
          elif [[ "$num_charts_changed" -eq "1" ]]; then
            echo "result=ok" >> "$GITHUB_OUTPUT"
            chart_name="${charts_dirs_changed//charts\/}"
            echo "chart=${chart_name}" >> "$GITHUB_OUTPUT"
            if [[ "${files_changed[*]}" =~ "charts/${chart_name}/values.yaml" ]]; then
              echo "values-updated=true" >> "$GITHUB_OUTPUT"
            fi
          fi
          
